# Generated by Django 5.1.4 on 2024-12-16 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosed',
            fields=[
                ('diag_id', models.AutoField(primary_key=True, serialize=False)),
                ('diag_descript', models.TextField()),
                ('diag_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('item_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_category_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Frame_Type',
            fields=[
                ('item_frame_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_frame_type_name', models.CharField(choices=[('Platic', 'Plastic'), ('Acetate', 'Acetate'), ('Metal', 'Metal'), ('Wood', 'Wood'), ('Titanium', 'Titanium')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mode_of_Payment',
            fields=[
                ('mop_id', models.AutoField(primary_key=True, serialize=False)),
                ('mop_name', models.CharField(choices=[('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('E Wallet', 'E Wallet')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Duration',
            fields=[
                ('payment_duration_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_duration_name', models.CharField(choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('9 Months', '9 Months'), ('12 Months', '12 Months')], max_length=50)),
                ('payment_duration_start', models.DateField(default=django.utils.timezone.now)),
                ('payment_duration_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Terms',
            fields=[
                ('pay_stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_stat_name', models.CharField(choices=[('Installment', 'Installment'), ('Fully Paid', 'Fully Paid')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_Item_Status',
            fields=[
                ('purchase_item_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_item_status_name', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Done', 'Done')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_code', models.AutoField(primary_key=True, serialize=False)),
                ('item_brand', models.CharField(max_length=200)),
                ('item_model', models.CharField(blank=True, max_length=20, null=True)),
                ('item_price', models.FloatField()),
                ('item_date_in', models.DateField(default=django.utils.timezone.now)),
                ('item_quantity', models.IntegerField()),
                ('item_color', models.CharField(blank=True, max_length=100, null=True)),
                ('item_measurement', models.CharField(blank=True, max_length=200, null=True)),
                ('item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruiz_clinic.item_category')),
                ('item_frame_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruiz_clinic.item_frame_type')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_payed', models.FloatField()),
                ('payment_to_be_payed', models.FloatField(blank=True, null=True)),
                ('mop_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.mode_of_payment')),
                ('payment_duration_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.payment_duration')),
                ('pay_stat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.payment_terms')),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_Item',
            fields=[
                ('pur_id', models.AutoField(primary_key=True, serialize=False)),
                ('pur_quantity', models.IntegerField()),
                ('pur_date_purchased', models.DateField(default=django.utils.timezone.now)),
                ('pur_total_price', models.FloatField()),
                ('item_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.item')),
                ('purchase_item_status_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.purchased_item_status')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_fname', models.CharField(max_length=50)),
                ('patient_lname', models.CharField(max_length=100)),
                ('patient_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('patient_address', models.CharField(max_length=400)),
                ('patient_occupation', models.CharField(blank=True, max_length=500, null=True)),
                ('patient_birthdate', models.DateField()),
                ('patient_contact', models.CharField(max_length=13)),
                ('diag_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruiz_clinic.diagnosed')),
                ('payment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.payment')),
                ('pur_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.purchased_item')),
            ],
        ),
    ]
