# Generated by Django 5.1.4 on 2024-12-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('app_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Waiting', 'Waiting')], max_length=50)),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.patient')),
            ],
        ),
    ]
