# Generated by Django 5.1.4 on 2024-12-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='app_fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
