# Generated by Django 5.1.4 on 2024-12-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0004_alter_appointment_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='app_contact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Waiting', 'Waiting'), ('Done', 'Done')], max_length=50),
        ),
    ]
