# Generated by Django 5.1.4 on 2024-12-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0004_alter_appointment_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_item',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.patient'),
        ),
    ]
