# Generated by Django 5.1.4 on 2024-12-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0005_purchased_item_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosed',
            name='diag_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
