# Generated by Django 5.1.4 on 2024-12-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0006_alter_diagnosed_diag_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosed',
            name='diag_date',
        ),
    ]
