# Generated by Django 5.1.4 on 2024-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0007_remove_diagnosed_diag_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diag_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_diag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Diagnosed',
        ),
    ]
