# Generated by Django 5.1.4 on 2024-12-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0008_remove_patient_diag_id_patient_patient_diag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.item_category'),
        ),
    ]
