# Generated by Django 5.1.4 on 2024-12-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0009_alter_item_item_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mop_id',
        ),
        migrations.RemoveField(
            model_name='purchased_item',
            name='pur_quantity',
        ),
        migrations.RemoveField(
            model_name='purchased_item',
            name='pur_total_price',
        ),
        migrations.AddField(
            model_name='item',
            name='item_date_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('E Wallet', 'E Wallet')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchased_item',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruiz_clinic.payment'),
        ),
        migrations.AlterField(
            model_name='purchased_item_status',
            name='purchase_item_status_name',
            field=models.CharField(choices=[('Wataing', 'Waiting'), ('For follow up', 'For follow up'), ('Done', 'Done')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Mode_of_Payment',
        ),
    ]
