# Generated by Django 5.1.4 on 2024-12-19 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0010_remove_payment_mop_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_date_checked_up',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
