# Generated by Django 5.1.4 on 2024-12-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0011_patient_patient_date_checked_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pay_stat_id',
        ),
        migrations.RemoveField(
            model_name='purchased_item',
            name='purchase_item_status_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('E Wallet', 'E Wallet'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('Installment', 'Installment'), ('Fully Paid', 'Fully Paid')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchased_item',
            name='pur_stat',
            field=models.CharField(choices=[('Waitinng', 'Waiting'), ('For follow up', 'For follow up'), ('Done', 'Done')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment_Terms',
        ),
        migrations.DeleteModel(
            name='Purchased_Item_Status',
        ),
    ]
