# Generated by Django 5.1.4 on 2024-12-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0014_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Waiting', 'Waiting'), ('Done', 'Done')], max_length=50),
        ),
    ]
