# Generated by Django 5.1.4 on 2024-12-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0015_alter_appointment_app_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_duration_id',
        ),
        migrations.AlterField(
            model_name='item_frame_type',
            name='item_frame_type_name',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Acetate', 'Acetate'), ('Metal', 'Metal'), ('Wood', 'Wood'), ('Titanium', 'Titanium')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Payment_Duration',
        ),
    ]
