# Generated by Django 5.1.4 on 2024-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0016_remove_payment_payment_duration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_payed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
