# Generated by Django 5.1.4 on 2024-12-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0017_alter_payment_payment_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_to_be_payed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchased_item',
            name='pur_stat',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('For follow up', 'For follow up'), ('Done', 'Done')], max_length=20),
        ),
    ]
