# Generated by Django 5.1.4 on 2024-12-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0018_alter_payment_payment_to_be_payed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_to_be_payed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
