# Generated by Django 5.1.4 on 2024-12-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0005_appointment_app_contact_alter_appointment_app_status'),
        ('ruiz_clinic', '0019_alter_payment_payment_to_be_payed'),
    ]

    operations = [
    ]
