# Generated by Django 5.1.4 on 2024-12-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0021_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_username',
            field=models.CharField(max_length=100),
        ),
    ]
