# Generated by Django 5.1.4 on 2024-12-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0022_alter_account_account_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_contact',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
    ]
