# Generated by Django 5.1.4 on 2025-01-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0023_account_account_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Waiting', 'Waiting'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
