# Generated by Django 5.1.4 on 2025-01-17 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0024_alter_appointment_app_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
