# Generated by Django 5.1.4 on 2025-01-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0021_item_item_name'),
        ('ruiz_clinic', '0025_alter_appointment_app_date'),
    ]

    operations = [
    ]
