# Generated by Django 5.1.4 on 2025-01-18 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0026_merge_20250117_1358'),
        ('ruiz_clinic', '0026_merge_20250117_1426'),
    ]

    operations = [
    ]
