# Generated by Django 5.1.4 on 2025-01-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0027_merge_20250117_2202'),
        ('ruiz_clinic', '0028_remove_account_account_contact_account_account_email_and_more'),
    ]

    operations = [
    ]
