# Generated by Django 5.1.4 on 2025-01-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0029_merge_20250118_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_item',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruiz_clinic.patient'),
        ),
        migrations.AlterField(
            model_name='purchased_item',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruiz_clinic.payment'),
        ),
    ]
