# Generated by Django 5.1.4 on 2025-01-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0027_merge_20250117_2202'),
        ('ruiz_clinic', '0029_remove_account_account_email'),
    ]

    operations = [
    ]
