# Generated by Django 5.1.4 on 2025-01-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0030_alter_purchased_item_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_item',
            name='pur_stat',
            field=models.CharField(choices=[('For Realease', 'For Release'), ('For follow up', 'For follow up'), ('Done', 'Done')], max_length=20),
        ),
    ]
