# Generated by Django 5.1.4 on 2025-01-20 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0030_merge_20250120_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('sales_total', models.FloatField(default=0.0)),
                ('number_products_sold', models.IntegerField(default=0)),
            ],
        ),
    ]
