# Generated by Django 5.1.4 on 2025-01-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0030_alter_purchased_item_patient_id_and_more'),
        ('ruiz_clinic', '0030_merge_20250120_2217'),
    ]

    operations = [
    ]
