# Generated by Django 5.1.4 on 2025-01-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0031_alter_purchased_item_pur_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_terms',
            field=models.CharField(choices=[('Installment', 'Installment'), ('Deposit', 'Deposit'), ('Fully Paid', 'Fully Paid')], default='Fully Paid', max_length=20),
        ),
    ]
