# Generated by Django 5.1.4 on 2025-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0032_alter_payment_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_item',
            name='pur_stat',
            field=models.CharField(choices=[('For Realease', 'For Release'), ('For follow up', 'For follow up'), ('Done', 'Done')], db_default='For Release', max_length=20),
        ),
    ]
