# Generated by Django 5.1.4 on 2025-01-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0033_alter_purchased_item_pur_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_date_out',
        ),
        migrations.AddField(
            model_name='purchased_item',
            name='item_date_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
