# Generated by Django 5.1.4 on 2025-01-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0029_remove_account_account_email'),
        ('ruiz_clinic', '0034_remove_item_item_date_out_and_more'),
    ]

    operations = [
    ]
