# Generated by Django 5.1.4 on 2025-01-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0035_merge_20250120_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='current_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
