# Generated by Django 5.1.4 on 2025-01-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0031_sales'),
        ('ruiz_clinic', '0037_payment_current_payment_date'),
    ]

    operations = [
    ]
