# Generated by Django 5.1.4 on 2025-01-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0031_merge_20250121_0242'),
        ('ruiz_clinic', '0038_merge_0031_sales_0037_payment_current_payment_date'),
    ]

    operations = [
    ]
