# Generated by Django 5.1.4 on 2025-01-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0039_merge_20250121_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_money',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
