# Generated by Django 5.1.4 on 2025-01-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0040_patient_patient_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_item',
            name='pur_stat',
            field=models.CharField(choices=[('For Release', 'For Release'), ('For follow up', 'For follow up'), ('Done', 'Done')], db_default='For Release', max_length=20),
        ),
    ]
