# Generated by Django 5.1.4 on 2025-01-21 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0042_payment_duration_payment_payment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_duration',
            name='payment_duration_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment_duration',
            name='payment_duration_span',
            field=models.CharField(blank=True, choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('9 Months', '9 Months'), ('12 Months', '12 Months')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment_duration',
            name='payment_duration_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
