# Generated by Django 5.1.4 on 2025-01-21 18:42

import ruiz_clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0043_alter_payment_duration_payment_duration_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_item',
            name='pur_date_purchased',
            field=models.DateField(default=ruiz_clinic.models.get_today_date),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_date',
            field=models.DateField(default=ruiz_clinic.models.get_today_date, unique=True),
        ),
    ]
