# Generated by Django 5.1.4 on 2025-01-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0044_alter_purchased_item_pur_date_purchased_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_money',
        ),
    ]
