# Generated by Django 5.1.4 on 2025-02-03 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0047_doctor_patient_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_date_checked_up',
        ),
        migrations.CreateModel(
            name='CheckUpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked_up', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_history', to='ruiz_clinic.patient')),
            ],
        ),
    ]
