# Generated by Django 5.1.4 on 2025-02-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0048_remove_patient_patient_date_checked_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkuphistory',
            name='notes',
        ),
    ]
