# Generated by Django 5.1.4 on 2025-02-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0049_remove_checkuphistory_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkuphistory',
            options={'get_latest_by': 'date_checked_up'},
        ),
    ]
